### PR TITLE
feat: move to esm (wip)

### PR DESCRIPTION
**Pull request by talentlessguy**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

This pull request add ESM support to mdast-util-from-markdown. Besides that, browserify is replaced with rollup, @rollup/plugin-babel and rollup-plugin-filesize.

At the moment some (8/714) tests fail.

Might happen because of this (https://github.com/talentlessguy/mdast-util-from-markdown/blob/f0a563441f1b8a75100c7ffd7726b884aa55b80b/lib/index.js#L38):

```js
const call = (y, x) => Object.hasOwnProperty.call(y, x)
```

but I'm not sure

full test run log: https://gist.github.com/talentlessguy/a880e53cec457c19ca3e2039959cccfb

hope this PR simplifies the process of moving to ESM :D

feel free to close it if it is invalid

### CODE REVIEW

**Comment by wooorm** [comment]
Hmm, appreciate the effort, thank you! But I’m already slowly moving through micromark and then this utility to port to ESM (ESM-only). I don’t think it’s a good idea to release this in the meanwhile. (I’m assuming some bigger things in markdown will change too before it reaches alpha -> beta).
If you *do* want to help, here’s how I’m applying the changes: https://github.com/micromark/micromark-extension-gfm-strikethrough/commits/main.

**Comment by talentlessguy** [comment]
@wooorm hello, sorry but I might not fully understand what you mean. Should we wait for micromark to get to beta in order for this to be merged?

also, the link you sent, do you mean I should align tooling and format to other ESM-ported projects? If yes, then it's not a problem, I can remove unnecessary tools and replace the ones that are used in your other libraries that you already moved to ESM

**Comment by wooorm** [comment]
> do you mean I should align tooling and format to other ESM-ported projects? If yes, then it's not a problem, I can remove unnecessary tools and replace the ones that are used in your other libraries that you already moved to ESM
>
> and should I use micromark-build for mdast-util-from-markdown? or those two aren't related

Yes, that’s what I meant.

---

Good news is that micromark is ready, assuming that this project can use it fine, too.

I really appreciate that you want to work on it, but I think it’s rather complex to get all of the micromark extensions and mdast utilities working correctly, in styled similarly, that I think it’s better for me to do it myself

What was your motivation for updating `mdast-util-from-markdown`? We do have lots of other issues that we could use some help with!

**Comment by talentlessguy** [comment]
@wooorm my motivation to update this package was to make [hypermdx](https://github.com/talentlessguy/hypermdx) (that uses unified and markdown utils) work with pure ESM. At the moment some CJS dependencies block that.

it depends on these:

```json
"hast-to-hyperscript": "^10.0.0",
"mdast-util-to-hast": "^11.1.1",
"remark-parse": "^9.0.0",
"unified": "^9.2.1"
```

and one of them depends on `mdast-util-from-markdown`...

sorry if I'm way too annoying with this, I just thought I could help to speed up the process of updating packages. I'm fully ok with waiting and I'd better help with other modules as you said.

**Comment by wooorm** [comment]
Not annoying at all! I just published the ESM beta: https://github.com/syntax-tree/mdast-util-from-markdown/releases/tag/1.0.0-beta.1.
There might be a few fixes in the actual v1, but I don’t expect any real changes!

**Comment by talentlessguy** [comment]
@wooorm omg thank you a lot!

**Pull request closed without merging**
